In [14]:
import scipy.io as sio
import pandas as pd

import numpy as np

import numpy.random as rand
from scipy.optimize import minimize

from surprise import Dataset, Reader

In [14]:
class FileReader:

    def __init__(self, file):
        self.file = file

    def read_file(self):
        if self:
            try:
                with open(self.file, "r", encoding="ISO-8859-1") as f:
                    movie_list = [' '.join(np.array(l.split())[1:]) for l in f.readlines()]
                return movie_list
            except IOError:
                pass
        else:
            raise ValueError("File name no specified. ")

In [75]:
class DATA():
    
    @staticmethod
    def readTXT(file):
        return FileReader('movie_ids.txt').read_file()
    
    @staticmethod
    def readMAT(file):
        return sio.loadmat(file)
    
    @staticmethod
    def loadData(file, fields = ['Y', 'R']):

        matData = DATA.readMAT(file)
        return [f for f in DATA.processData(matData, fields)]
    
    @staticmethod
    def processData(matData, fields):
        
        if type(fields) is str:
            yield matData[fields]
        elif type(fields) is list:
            for f in fields:
                yield matData[f]
        else:
            raise TypeError('value of {} can be either string or list, provided is {} '.format("'fields'", type(fields)))


[[5 4 0 ... 5 0 0]
 [3 0 0 ... 0 0 5]
 [4 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[1 1 0 ... 1 0 0]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
#pd.DataFrame(rawData)

0    1    2    3    4    5    6    7    8    9    ...  933  934  935  \
0       5    4    0    0    4    4    0    0    0    4  ...    2    3    4   
1       3    0    0    0    3    0    0    0    0    0  ...    4    0    0   
2       4    0    0    0    0    0    0    0    0    0  ...    0    0    4   
3       3    0    0    0    0    0    5    0    0    4  ...    5    0    0   
4       3    0    0    0    0    0    0    0    0    0  ...    0    0    0   
5       5    0    0    0    0    0    0    0    5    0  ...    0    0    5   
6       4    0    0    0    0    2    5    3    4    4  ...    0    0    4   
7       1    0    0    0    0    4    5    0    0    0  ...    0    0    0   
8       5    0    0    0    0    4    5    0    0    4  ...    0    1    4   
9       3    2    0    0    0    0    4    0    0    0  ...    0    0    0   
10      2    0    0    4    0    0    3    3    0    4  ...    0    0    0   
11      5    0    0    0    0    4    5    0    0    5  ...    0    0    0   
12      5    4    0    0    0    2    0    0    0    3  ...    5    0    4   
13      5    4    0    0    0    5    0    0    0    0  ...    0    0    4   
14      5    0    0    0    0    3    0    0    0    0  ...    0    5    0   
15      5    0    0    0    0    0    0    0    0    4  ...    0    0    4   
16      3    0    0    0    4    0    0    0    0    0  ...    0    0    0   
17      4    0    0    0    0    0    0    0    0    0  ...    0    0    0   
18      5    3    0    0    0    4    0    0    0    0  ...    0    0    5   
19      4    0    0    0    0    0    0    0    0    0  ...    0    0    5   
20      1    0    0    0    3    3    0    0    0    0  ...    0    0    0   
21      4    0    0    0    0    3    5    5    0    5  ...    0    0    0   
22      4    0    0    0    0    4    3    0    0    5  ...    0    0    0   
23      3    0    0    0    4    0    0    0    0    0  ...    0    0    4   
24      4    4    0    0    3    0    3    0    0    0  ...    4    0    4   
25      3    0    0    0    0    0    0    0    0    0  ...    0    0    0   
26      2    0    0    0    0    0    4    0    0    0  ...    0    0    0   
27      4    0    0    0    0    2    5    0    0    0  ...    0    0    0   
28      1    0    0    0    4    0    3    0    0    0  ...    0    0    0   
29      3    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1652    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1653    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1654    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1655    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1656    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1657    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1658    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1659    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1660    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1661    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1662    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1663    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1664    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1665    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1666    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1667    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1668    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1669    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1670    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1671    0    0    0    0    